name: Auto Sync to project repos

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Configure git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"

      - name: Sync to project repos
        run: |
          git remote remove mirror || true
          git remote add mirror https://x-access-token:${{ secrets.FARIDABAD_ACESS_TOKEN }}@github.com/dealacresfaridabad/2BHK-Flat-for-sale.git
          git push mirror HEAD:main --force
