name: Auto Sync to project repos

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Configure git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"

      # Existing Gurgaon Repo
      # - name: Sync to Gurgaon Repo
      #   continue-on-error: true
      #   run: |
      #     git remote remove mirror || true
      #     git remote add mirror https://x-access-token:${{ secrets.GURGAON_ACCESS_TOKEN }}@github.com/dealacresGurgaon/2-BHK-Flat-For-Sale.git
      #     git push mirror HEAD:main --force

      # Gurgaon Projects Repo
      - name: Sync to Gurgaon Projects Repo
        continue-on-error: true
        run: |
          git remote remove projects || true
          git remote add projects https://x-access-token:${{ secrets.MUKESH_PROJECTS_ACCESS_TOKEN }}@github.com/mukeshkumar44/gurgaon-2bhk-flate.git
          git push projects HEAD:main --force

      # Nagori Gate Repo
      - name: Sync to Nagori Gate 2 BHK Flat For Sale
        continue-on-error: true
        run: |
          git remote remove nagori || true
          git remote add nagori https://x-access-token:${{ secrets.NAGORI_GATE_PROJECTS_ACCESS_TOKEN }}@github.com/dealacresnagorigate/2-bhk-flat-for-sale.git
          git push nagori HEAD:main --force